# Generated by Django 6.0.7 on 2026-08-05 10:55

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_category_image_alter_gameimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='games/videos/'),
        ),
    ]
