# Generated by Django 6.0.7 on 2026-08-07 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='system_requirements',
            field=models.JSONField(blank=True, default=dict, help_text="Format: {'minimum': {'os': '...', 'ram': '...'}, 'recommended': {...}}", null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='games.studio'),
        ),
    ]
