# Generated by Django 6.0.7 on 2026-08-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_studio_game_system_requirements_game_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='system_requirements',
            field=models.JSONField(blank=True, default=dict, help_text='\n    Example:\n    {\n        "os": "Windows 11 64-bit",\n        "processor": "Intel Core i5-12400F",\n        "memory": "16 GB RAM",\n        "graphics": "NVIDIA RTX 3060",\n        "storage": "80 GB",\n        "directx": "Version 12"\n    }\n    ', null=True),
        ),
    ]
