# Generated by Django 6.0.7 on 2026-08-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_system_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.TextField(help_text='Example: PC, PS5, Xbox Series X'),
        ),
    ]
