# Generated by Django 6.0.7 on 2026-08-07 17:13

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='video',
            field=models.FileField(blank=True, max_length=500, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='games/videos/'),
        ),
    ]
