# Generated by Django 6.0.7 on 2026-08-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_game_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, help_text='Example: Rockstar, Ubisoft, Mojang', max_length=255),
        ),
    ]
