# Generated by Django 6.0.7 on 2026-09-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_game_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='system_requirements',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Example:\n        {\n            "os": "Windows 11 64-bit",\n            "processor": "Intel Core i5-12400F",\n            "memory": "16 GB RAM",\n            "graphics": "NVIDIA RTX 3060",\n            "storage": "80 GB",\n            "directx": "Version 12"\n        }\n        ', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='video',
            field=models.URLField(blank=True, help_text='Paste YouTube, Vimeo, or direct video URL', max_length=500, null=True),
        ),
    ]
